image: quay.io/ansible/toolset

stages:
  - lint

before_script:
  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

molecule_static_analyse:
  stage: lint
  script:
    - molecule lint --scenario-name default
    - molecule syntax --scenario-name default
  tags:
    - docker
