image: quay.io/ansible/toolset:latest

stages:
  - lint
  - test

#molecule_lint:

molecule_test:
  stage: test
  before_script:
    - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - source "/root/.bashrc"
    - apt-get update
    - apt-get -y install openssh-client
    - ssh-keygen -t ed25519 -b 256 -P "" -f ~/ssh_key
    - >
      yc compute instance create 
        --name molecule-ubuntu-2004-lts
        --zone ru-central1-b
        --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-2004-lts
        --ssh-key ~/ssh_key.pub
  script:
    - molecule lint --scenario-name default
    - molecule syntax --scenario-name default
  after_script:
    - yc compute instance delete --name molecule-ubuntu-2004-lts
  tags:
    - docker
