image: quay.io/ansible/toolset

stages:
  - lint

before_script:
  - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - apt-get -y install openssh-client
  - ssh-keygen -t ed25519 -b 256 -P "" -f ~/ssh_key
  - >
    yc compute instance create 
      --name molecule-ubuntu-2004-lts
      --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-2004-lts
      --ssh-key ~/ssh_key.pub

molecule_static_analyse:
  stage: lint
  script:
    - molecule lint --scenario-name default
    - molecule syntax --scenario-name default
  tags:
    - docker

after_script:
  - yc compute instance delete --name molecule-ubuntu-2004-lts
