image: quay.io/ansible/toolset:latest

stages:
  - lint
  - test

molecule_lint:
  stage: lint
  script:
    - molecule lint
  tags:
    - docker

molecule_test:
  stage: test
  before_script:
    - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - source "/root/.bashrc"
    - apt-get update
    - apt-get -y install openssh-client jq
    # - ssh-keygen -t ed25519 -b 256 -P "" -f ~/ssh_key
    # - >
    #   yc compute instance create \
    #     --zone ru-central1-b \
    #     --name molecule-ubuntu-2004-lts \
    #     --network-interface subnet-name=gitlb-runner-subnet \
    #     --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-2004-lts \
    #     --ssh-key ~/ssh_key.pub
  script:
    - molecule create --scenario-name yandex-cloud-ci
    - cat "/tmp/ssh_key"
    - cat "/tmp/ssh_key.pub"
  # after_script:
  #   - yc compute instance delete --name molecule-ubuntu-2004-lts
  tags:
    - docker
