---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#tag-inheritance-for-includes-blocks-and-the-apply-keyword
- name: Include vars with any tags
  block:
    - name: Include os-specific variables
      include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - always

- name: Prepare target host
  block:
    - include_tasks: "prepare_{{ ansible_distribution }}.yml"
  when: vector_prepare | bool
  tags:
    - vector
    - vector_prepare

- name: Install vector
  block:
    - include_tasks: "install_{{ ansible_distribution }}.yml"
  when: vector_install | bool
  tags:
    - vector
    - vector_install

- name: configure vector
  import_tasks: configure.yml
  when: vector_configure | bool
  tags:
    - vector
    - vector_configure

- name: Provide system service for vector
  import_tasks: service.yml
  when: vector_service | bool
  tags:
    - vector
    - vector_service
