---
- name: Provide vector.service autostart status
  systemd:
    name: vector
    enabled: "{{ vector_service_enabled | bool }}"

- name: Provide vector.service status
  systemd:
    name: vector
    state: "{{ vector_service_status }}"
